version: '3.8'

services:
  app:
    build: 
      context: .
      dockerfile: .docker/Dockerfile.dev
    image: role-patrocinado
    container_name: role-patrocinado
    entrypoint: sh .docker/entrypoint.sh
    volumes:
      - .:/usr/app/roles-patrocinado