CREATE DATABASE sponsored_outing;

\c sponsored_outing;

CREATE TABLE users (
    "id" VARCHAR(100) NOT NULL,
    "name" VARCHAR(20) NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE outings (
    "id" VARCHAR(100) NOT NULL,
    "place_name" VARCHAR(20) NOT NULL,
    "service_fee" DECIMAL(10, 2) NOT NULL,
    "date" DATE NOT NULL,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE members (
    "id" VARCHAR(100) NOT NULL,
    "outing_id" VARCHAR(100) NOT NULL,
    "user_id" VARCHAR(100) NOT NULL,
    "is_guest" BOOLEAN NOT NULL DEFAULT FALSE,
    "is_sponsor" BOOLEAN NOT NULL DEFAULT FALSE,
    "sponsored_value" DECIMAL(10, 2) NOT NULL DEFAULT 0,
    "created_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    "updated_at" TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);
